### ISSUE TITLE
ScanBarcodeOptions.codeType does not allow for a selection of codeTypes

### ISSUE THREAD

**Issue by mschmid** [gev2002/react-native-vision-camera-v3-barcode-scanner#3]
I prefer using this module because it uses mlkit also for iOS.

However with the current implementation, I can select only one specific codeType or `all`.
It would be preferable to pass an array of codeTypes, just like in the `react-native-vision-camera`.

**Comment by gev2002** [comment]
> I prefer using this module because it uses mlkit also for iOS.
> 
> However with the current implementation, I can select only one specific codeType or `all`. It would be preferable to pass an array of codeTypes, just like in the `react-native-vision-camera`.

Good Idea.  I will do it soon.
